export const data = [
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Nike Running Shoes",
        sellerName : "Retailsnet",
        sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Puma Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Titan Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fossil Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    },
    {
        product : "Reebok Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 20,
        defectiveQuantity : 2,
        comment : "Different Color",
        buyerName : "Pravin Poshmani",
        buyerEmail : "Pravin@xyz.com",
        buyerMobile : 345678976,
        shippedDate : "02-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Pending",
        staffName : "Honey Singh",
        staffId : "EMP002"
    },
    {
        product : "Timex Watch",
        sellerName : "Titan co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Komal Kamble",
        buyerEmail : "Komal@xyz.com",
        buyerMobile : 9876678976,
        shippedDate : "03-12-2020",
        deliveredDate : "05-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Neha Kakkar",
        staffId : "EMP003"
    },
    {
        product : "Fila Running Shoes",
        sellerName : "Retailsnet",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 30,
        defectiveQuantity : 2,
        comment : "sole damaged",
        buyerName : "Tejas Thakare",
        buyerEmail : "Tejas@xyz.com",
        buyerMobile : 12345678976,
        shippedDate : "01-12-2020",
        deliveredDate : "04-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Arijit Singh",
        staffId : "EMP001"
    },
    {
        product : "Fastrack Watch",
        sellerName : "Fossil co",
         sellerEmail : "reati@xyz.com",
        sellerMobile : 98765432,
        totalQuantitySent : 25,
        defectiveQuantity : 3,
        comment : "Sctratches on dial",
        buyerName : "Himanshu Chanda",
        buyerEmail : "Himanshu@xyz.com",
        buyerMobile : 8898766786,
        shippedDate : "04-12-2020",
        deliveredDate : "09-21-2020",
        bidoyaFlag : "Checked",
        staffName : "Kumar Sanu",
        staffId : "EMP004"
    }
   
]


export const columns = [
    {
      name: 'Product',
      selector: 'product',
      sortable: true,
      minWidth: '200px'
    },
    {
      name: 'Seller Name',
      selector: 'sellerName',
      sortable: true,
      minWidth: '200px'
    },
    {
      name: 'Seller Email',
      selector: 'sellerEmail',
      sortable: true,
      minWidth: '200px'
    },
    {
      name: 'Seller Mobile Number',
      selector: 'sellerMobile',
      sortable: true,
      minWidth: '200px'
    },
    {
        name: 'Toatl Quantity Sent',
        selector: 'totalQuantitySent',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Defective Quantity',
        selector: 'defectiveQuantity',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Comment',
        selector: 'comment',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Buyer Name',
        selector: 'buyerName',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Buyer Email',
        selector: 'buyerEmail',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Buyer Mobile',
        selector: 'buyerMobile',
        sortable: true,
        minWidth: '200px'
      },
      {
        name: 'Shipped Date',
        selector: 'shippedDate',
        sortable: true,
        minWidth: '200px'
    },
    {
        name: 'Delivered Date',
        selector: 'deliveredDate',
        sortable: true,
        minWidth: '200px'
    },
    {
        name: 'Bidoya Flag',
        selector: 'bidoyaFlag',
        sortable: true,
        minWidth: '200px'
    },
    {
        name: 'Staff Name',
        selector: 'staffName',
        sortable: true,
        minWidth: '200px'
    },
    {
      name: "Staff's EMP ID",
      selector: 'staffId',
      sortable: true,
      minWidth: '200px'
  }
]