//Name,
//Email, 
//Designation(CEO of TCS),
//phone
 
import komal  from '@src/assets/images/logo/komal.jpg'
import pravin  from '@src/assets/images/logo/pravin.jpg'
import himanshu  from '@src/assets/images/logo/himanshu.jpg'
import reethika  from '@src/assets/images/logo/reethika.jpg'


//expot data
export const data = [

  {
    id:1,
    Employee_Name : "Komal Kamble",
    Client : "Umang Shah",
    Employee_Email : "komal@gmail.com", // Used By 
    Client_Email : "umang@gmail.com", //Generated By
    PIN : "9817",
    PIN_ID : "#001",
    Reason : "Client was out of Office",
    PIN_Generate_Time : "12 Jun 2021 3 PM",
    Login_Time :  "12 Jun 2021 4 PM",
    Logout_Time :  "12 Jun 2021 5 PM",
    Duration : "1 Hr",
       avatar: ""
  }
  
]
