
import komal  from '../../../assets/images/logo/komal.jpg'
import pravin  from '../../../assets/images/logo/pravin.jpg'
import himanshu  from '../../../assets/images/logo/himanshu.jpg'
import reethika  from '../../../assets/images/logo/reethika.jpg'


//expot data
export const data = [
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      },
      {
        id:1,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K", 
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"tejas",
        utilized_by:"Tejas" 
      },
      {
        id:2,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:pravin,
        username:"pravinn2",
        utilized_by:"Pravin"
      },
      {
        id:3,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:komal,
        username:"komal12",
        utilized_by:"Komal"
      },
      {
        id:4,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:'',
        username:"mehulq1",
       utilized_by:"Mehul"
      },
      {
        id:5,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"harpriya23",
        utilized_by:"Harpriya"
      },
      {
        id:6,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:reethika,
        username:"Reethika45",
        utilized_by:"Reethika"
      },
      {
        id:7,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"himanshu23",
        utilized_by:"Himanshu"
      },
      {
        id:8,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"suryadas",
        utilized_by:"Surya_Das"
      },
      {
        id:9,
        bid_id : "Bid231",
        cash_utilizated: 2321,
        balance: "200K",
        user_id: 1324,
        Date: `${new Date().toGMTString()}`,
        avatar:"",
        username:"avinash",
        utilized_by:"Avinash"
      }
]
