import komal  from '@src/assets/images/logo/komal.jpg'
import pravin  from '@src/assets/images/logo/pravin.jpg'
import himanshu  from '@src/assets/images/logo/himanshu.jpg'
import reethika  from '@src/assets/images/logo/reethika.jpg'

//expot data
export const data = [
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 1,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 2,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 3,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 4,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 5,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 6,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 7,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 8,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 9,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 10,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 11,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 12,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 13,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 14,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 15,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 16,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 17,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 18,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 19,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 20,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 21,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 22,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 23,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 24,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 25,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 26,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 27,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 28,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 29,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 30,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 31,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 32,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 33,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 34,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 35,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 800,
        id: 36,
        rate : 250,
        quantity : "10hr",
        D_Name : "Komal Kamble",
        username: "pravin",
        avatar: komal,
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 37,
        rate : 700,
        quantity : "20hr",
        D_Name : "Pravin Poshmani",
        username: "komal",
        avatar: pravin,
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 38,
        rate : 700,
        quantity : "30hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Web devlopment",
        Cost: 300,
        id: 39,
        rate : 650,
        quantity : "40hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Minutes"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "instagram manager",
        Cost: 750,
        id: 40,
        rate : 700,
        quantity : "50hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "editor",
        Cost: 400,
        id: 41,
        rate : 340,
        quantity : "60hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      },
      {
        Date: `${new Date().toGMTString()}`, 
        behalf:"",
        Name: "Keyword finder",
        Cost: 200,
        id: 42,
        rate : 700,
        quantity : "70hr",
        D_Name : "Pravin Poshmani",
        username: "pravin",
        avatar: "",
        unit : "Hours"
      }
     
]
