export const data = [
    {
      toEmail : "Pravin Poshmani",
      emailName : "Complaint",
      emailId : "123@abc.com",
      ccEmail : "12@abc.com",
      bccEmail : "11@abc.com",
      fromEmail : "pravin@abc.com",
      subject : "Reg - Product Damage issue",
      body : "Product Damage issue in Area",
      priority : "High",
      status : "Delivered",
      type : "Type1",
      sendTime : "11-12-2021"
    },
    {
        toEmail : "Tejas Thakare",
        emailName : "Invoice",
        emailId : "223@abc.com",
        ccEmail : "22@abc.com",
        bccEmail : "22@abc.com",
        fromEmail : "tejas@abc.com",
        subject : "Reg - Invoice",
        body : "Didnt receive Invoice",
        priority : "High",
        status : "Delivered",
        type : "Type2",
        sendTime : "22-12-2021"
    },
    {
        toEmail : "Komal Kamble",
        emailName : "Profile",
        emailId : "323@abc.com",
        ccEmail : "32@abc.com",
        bccEmail : "33@abc.com",
        fromEmail : "komal@abc.com",
        subject : "Reg - Profile Updation",
        body : "Profile didnt updated",
        priority : "High",
        status : "Delivered",
        type : "Type3",
        sendTime : "30-02-2023"
    },
    {
        toEmail : "Daksh",
        emailName : "Order",
        emailId : "423@abc.com",
        ccEmail : "42@abc.com",
        bccEmail : "44@abc.com",
        fromEmail : "daksh@abc.com",
        subject : "Reg - Order",
        body : "Order isnt geting placed",
        priority : "High",
        status : "Delivered",
        type : "Type4",
        sendTime : "04-12-2024"
    },
    {
        toEmail : "Pravin Poshmani",
        emailName : "Complaint",
        emailId : "123@abc.com",
        ccEmail : "12@abc.com",
        bccEmail : "11@abc.com",
        fromEmail : "pravin@abc.com",
        subject : "Reg - Product Damage issue",
        body : "Product Damage issue in Area",
        priority : "High",
        status : "Delivered",
        type : "Type1",
        sendTime : "11-12-2021"
      },
      {
          toEmail : "Tejas Thakare",
          emailName : "Invoice",
          emailId : "223@abc.com",
          ccEmail : "22@abc.com",
          bccEmail : "22@abc.com",
          fromEmail : "tejas@abc.com",
          subject : "Reg - Invoice",
          body : "Didnt receive Invoice",
          priority : "High",
          status : "Delivered",
          type : "Type2",
          sendTime : "22-12-2021"
      },
      {
          toEmail : "Komal Kamble",
          emailName : "Profile",
          emailId : "323@abc.com",
          ccEmail : "32@abc.com",
          bccEmail : "33@abc.com",
          fromEmail : "komal@abc.com",
          subject : "Reg - Profile Updation",
          body : "Profile didnt updated",
          priority : "High",
          status : "Delivered",
          type : "Type3",
          sendTime : "30-02-2023"
      },
      {
          toEmail : "Daksh",
          emailName : "Order",
          emailId : "423@abc.com",
          ccEmail : "42@abc.com",
          bccEmail : "44@abc.com",
          fromEmail : "daksh@abc.com",
          subject : "Reg - Order",
          body : "Order isnt geting placed",
          priority : "High",
          status : "Delivered",
          type : "Type4",
          sendTime : "04-12-2024"
      },
      {
        toEmail : "Pravin Poshmani",
        emailName : "Complaint",
        emailId : "123@abc.com",
        ccEmail : "12@abc.com",
        bccEmail : "11@abc.com",
        fromEmail : "pravin@abc.com",
        subject : "Reg - Product Damage issue",
        body : "Product Damage issue in Area",
        priority : "High",
        status : "Delivered",
        type : "Type1",
        sendTime : "11-12-2021"
      },
      {
          toEmail : "Tejas Thakare",
          emailName : "Invoice",
          emailId : "223@abc.com",
          ccEmail : "22@abc.com",
          bccEmail : "22@abc.com",
          fromEmail : "tejas@abc.com",
          subject : "Reg - Invoice",
          body : "Didnt receive Invoice",
          priority : "High",
          status : "Delivered",
          type : "Type2",
          sendTime : "22-12-2021"
      },
      {
          toEmail : "Komal Kamble",
          emailName : "Profile",
          emailId : "323@abc.com",
          ccEmail : "32@abc.com",
          bccEmail : "33@abc.com",
          fromEmail : "komal@abc.com",
          subject : "Reg - Profile Updation",
          body : "Profile didnt updated",
          priority : "High",
          status : "Delivered",
          type : "Type3",
          sendTime : "30-02-2023"
      },
      {
          toEmail : "Daksh",
          emailName : "Order",
          emailId : "423@abc.com",
          ccEmail : "42@abc.com",
          bccEmail : "44@abc.com",
          fromEmail : "daksh@abc.com",
          subject : "Reg - Order",
          body : "Order isnt geting placed",
          priority : "High",
          status : "Delivered",
          type : "Type4",
          sendTime : "04-12-2024"
      },
      {
          toEmail : "Pravin Poshmani",
          emailName : "Complaint",
          emailId : "123@abc.com",
          ccEmail : "12@abc.com",
          bccEmail : "11@abc.com",
          fromEmail : "pravin@abc.com",
          subject : "Reg - Product Damage issue",
          body : "Product Damage issue in Area",
          priority : "High",
          status : "Delivered",
          type : "Type1",
          sendTime : "11-12-2021"
        },
        {
            toEmail : "Tejas Thakare",
            emailName : "Invoice",
            emailId : "223@abc.com",
            ccEmail : "22@abc.com",
            bccEmail : "22@abc.com",
            fromEmail : "tejas@abc.com",
            subject : "Reg - Invoice",
            body : "Didnt receive Invoice",
            priority : "High",
            status : "Delivered",
            type : "Type2",
            sendTime : "22-12-2021"
        },
        {
            toEmail : "Komal Kamble",
            emailName : "Profile",
            emailId : "323@abc.com",
            ccEmail : "32@abc.com",
            bccEmail : "33@abc.com",
            fromEmail : "komal@abc.com",
            subject : "Reg - Profile Updation",
            body : "Profile didnt updated",
            priority : "High",
            status : "Delivered",
            type : "Type3",
            sendTime : "30-02-2023"
        },
        {
            toEmail : "Daksh",
            emailName : "Order",
            emailId : "423@abc.com",
            ccEmail : "42@abc.com",
            bccEmail : "44@abc.com",
            fromEmail : "daksh@abc.com",
            subject : "Reg - Order",
            body : "Order isnt geting placed",
            priority : "High",
            status : "Delivered",
            type : "Type4",
            sendTime : "04-12-2024"
        },
        {
            toEmail : "Pravin Poshmani",
            emailName : "Complaint",
            emailId : "123@abc.com",
            ccEmail : "12@abc.com",
            bccEmail : "11@abc.com",
            fromEmail : "pravin@abc.com",
            subject : "Reg - Product Damage issue",
            body : "Product Damage issue in Area",
            priority : "High",
            status : "Delivered",
            type : "Type1",
            sendTime : "11-12-2021"
          },
          {
              toEmail : "Tejas Thakare",
              emailName : "Invoice",
              emailId : "223@abc.com",
              ccEmail : "22@abc.com",
              bccEmail : "22@abc.com",
              fromEmail : "tejas@abc.com",
              subject : "Reg - Invoice",
              body : "Didnt receive Invoice",
              priority : "High",
              status : "Delivered",
              type : "Type2",
              sendTime : "22-12-2021"
          },
          {
              toEmail : "Komal Kamble",
              emailName : "Profile",
              emailId : "323@abc.com",
              ccEmail : "32@abc.com",
              bccEmail : "33@abc.com",
              fromEmail : "komal@abc.com",
              subject : "Reg - Profile Updation",
              body : "Profile didnt updated",
              priority : "High",
              status : "Delivered",
              type : "Type3",
              sendTime : "30-02-2023"
          },
          {
              toEmail : "Daksh",
              emailName : "Order",
              emailId : "423@abc.com",
              ccEmail : "42@abc.com",
              bccEmail : "44@abc.com",
              fromEmail : "daksh@abc.com",
              subject : "Reg - Order",
              body : "Order isnt geting placed",
              priority : "High",
              status : "Delivered",
              type : "Type4",
              sendTime : "04-12-2024"
          },
          {
              toEmail : "Pravin Poshmani",
              emailName : "Complaint",
              emailId : "123@abc.com",
              ccEmail : "12@abc.com",
              bccEmail : "11@abc.com",
              fromEmail : "pravin@abc.com",
              subject : "Reg - Product Damage issue",
              body : "Product Damage issue in Area",
              priority : "High",
              status : "Delivered",
              type : "Type1",
              sendTime : "11-12-2021"
            },
            {
                toEmail : "Tejas Thakare",
                emailName : "Invoice",
                emailId : "223@abc.com",
                ccEmail : "22@abc.com",
                bccEmail : "22@abc.com",
                fromEmail : "tejas@abc.com",
                subject : "Reg - Invoice",
                body : "Didnt receive Invoice",
                priority : "High",
                status : "Delivered",
                type : "Type2",
                sendTime : "22-12-2021"
            },
            {
                toEmail : "Komal Kamble",
                emailName : "Profile",
                emailId : "323@abc.com",
                ccEmail : "32@abc.com",
                bccEmail : "33@abc.com",
                fromEmail : "komal@abc.com",
                subject : "Reg - Profile Updation",
                body : "Profile didnt updated",
                priority : "High",
                status : "Delivered",
                type : "Type3",
                sendTime : "30-02-2023"
            },
            {
                toEmail : "Daksh",
                emailName : "Order",
                emailId : "423@abc.com",
                ccEmail : "42@abc.com",
                bccEmail : "44@abc.com",
                fromEmail : "daksh@abc.com",
                subject : "Reg - Order",
                body : "Order isnt geting placed",
                priority : "High",
                status : "Delivered",
                type : "Type4",
                sendTime : "04-12-2024"
            },
            {
                toEmail : "Pravin Poshmani",
                emailName : "Complaint",
                emailId : "123@abc.com",
                ccEmail : "12@abc.com",
                bccEmail : "11@abc.com",
                fromEmail : "pravin@abc.com",
                subject : "Reg - Product Damage issue",
                body : "Product Damage issue in Area",
                priority : "High",
                status : "Delivered",
                type : "Type1",
                sendTime : "11-12-2021"
              },
              {
                  toEmail : "Tejas Thakare",
                  emailName : "Invoice",
                  emailId : "223@abc.com",
                  ccEmail : "22@abc.com",
                  bccEmail : "22@abc.com",
                  fromEmail : "tejas@abc.com",
                  subject : "Reg - Invoice",
                  body : "Didnt receive Invoice",
                  priority : "High",
                  status : "Delivered",
                  type : "Type2",
                  sendTime : "22-12-2021"
              },
              {
                  toEmail : "Komal Kamble",
                  emailName : "Profile",
                  emailId : "323@abc.com",
                  ccEmail : "32@abc.com",
                  bccEmail : "33@abc.com",
                  fromEmail : "komal@abc.com",
                  subject : "Reg - Profile Updation",
                  body : "Profile didnt updated",
                  priority : "High",
                  status : "Delivered",
                  type : "Type3",
                  sendTime : "30-02-2023"
              },
              {
                  toEmail : "Daksh",
                  emailName : "Order",
                  emailId : "423@abc.com",
                  ccEmail : "42@abc.com",
                  bccEmail : "44@abc.com",
                  fromEmail : "daksh@abc.com",
                  subject : "Reg - Order",
                  body : "Order isnt geting placed",
                  priority : "High",
                  status : "Delivered",
                  type : "Type4",
                  sendTime : "04-12-2024"
              },
              {
                  toEmail : "Pravin Poshmani",
                  emailName : "Complaint",
                  emailId : "123@abc.com",
                  ccEmail : "12@abc.com",
                  bccEmail : "11@abc.com",
                  fromEmail : "pravin@abc.com",
                  subject : "Reg - Product Damage issue",
                  body : "Product Damage issue in Area",
                  priority : "High",
                  status : "Delivered",
                  type : "Type1",
                  sendTime : "11-12-2021"
                },
                {
                    toEmail : "Tejas Thakare",
                    emailName : "Invoice",
                    emailId : "223@abc.com",
                    ccEmail : "22@abc.com",
                    bccEmail : "22@abc.com",
                    fromEmail : "tejas@abc.com",
                    subject : "Reg - Invoice",
                    body : "Didnt receive Invoice",
                    priority : "High",
                    status : "Delivered",
                    type : "Type2",
                    sendTime : "22-12-2021"
                },
                {
                    toEmail : "Komal Kamble",
                    emailName : "Profile",
                    emailId : "323@abc.com",
                    ccEmail : "32@abc.com",
                    bccEmail : "33@abc.com",
                    fromEmail : "komal@abc.com",
                    subject : "Reg - Profile Updation",
                    body : "Profile didnt updated",
                    priority : "High",
                    status : "Delivered",
                    type : "Type3",
                    sendTime : "30-02-2023"
                },
                {
                    toEmail : "Daksh",
                    emailName : "Order",
                    emailId : "423@abc.com",
                    ccEmail : "42@abc.com",
                    bccEmail : "44@abc.com",
                    fromEmail : "daksh@abc.com",
                    subject : "Reg - Order",
                    body : "Order isnt geting placed",
                    priority : "High",
                    status : "Delivered",
                    type : "Type4",
                    sendTime : "04-12-2024"
                },
                {
                    toEmail : "Pravin Poshmani",
                    emailName : "Complaint",
                    emailId : "123@abc.com",
                    ccEmail : "12@abc.com",
                    bccEmail : "11@abc.com",
                    fromEmail : "pravin@abc.com",
                    subject : "Reg - Product Damage issue",
                    body : "Product Damage issue in Area",
                    priority : "High",
                    status : "Delivered",
                    type : "Type1",
                    sendTime : "11-12-2021"
                  },
                  {
                      toEmail : "Tejas Thakare",
                      emailName : "Invoice",
                      emailId : "223@abc.com",
                      ccEmail : "22@abc.com",
                      bccEmail : "22@abc.com",
                      fromEmail : "tejas@abc.com",
                      subject : "Reg - Invoice",
                      body : "Didnt receive Invoice",
                      priority : "High",
                      status : "Delivered",
                      type : "Type2",
                      sendTime : "22-12-2021"
                  },
                  {
                      toEmail : "Komal Kamble",
                      emailName : "Profile",
                      emailId : "323@abc.com",
                      ccEmail : "32@abc.com",
                      bccEmail : "33@abc.com",
                      fromEmail : "komal@abc.com",
                      subject : "Reg - Profile Updation",
                      body : "Profile didnt updated",
                      priority : "High",
                      status : "Delivered",
                      type : "Type3",
                      sendTime : "30-02-2023"
                  },
                  {
                      toEmail : "Daksh",
                      emailName : "Order",
                      emailId : "423@abc.com",
                      ccEmail : "42@abc.com",
                      bccEmail : "44@abc.com",
                      fromEmail : "daksh@abc.com",
                      subject : "Reg - Order",
                      body : "Order isnt geting placed",
                      priority : "High",
                      status : "Delivered",
                      type : "Type4",
                      sendTime : "04-12-2024"
                  },
                  {
                      toEmail : "Pravin Poshmani",
                      emailName : "Complaint",
                      emailId : "123@abc.com",
                      ccEmail : "12@abc.com",
                      bccEmail : "11@abc.com",
                      fromEmail : "pravin@abc.com",
                      subject : "Reg - Product Damage issue",
                      body : "Product Damage issue in Area",
                      priority : "High",
                      status : "Delivered",
                      type : "Type1",
                      sendTime : "11-12-2021"
                    },
                    {
                        toEmail : "Tejas Thakare",
                        emailName : "Invoice",
                        emailId : "223@abc.com",
                        ccEmail : "22@abc.com",
                        bccEmail : "22@abc.com",
                        fromEmail : "tejas@abc.com",
                        subject : "Reg - Invoice",
                        body : "Didnt receive Invoice",
                        priority : "High",
                        status : "Delivered",
                        type : "Type2",
                        sendTime : "22-12-2021"
                    },
                    {
                        toEmail : "Komal Kamble",
                        emailName : "Profile",
                        emailId : "323@abc.com",
                        ccEmail : "32@abc.com",
                        bccEmail : "33@abc.com",
                        fromEmail : "komal@abc.com",
                        subject : "Reg - Profile Updation",
                        body : "Profile didnt updated",
                        priority : "High",
                        status : "Delivered",
                        type : "Type3",
                        sendTime : "30-02-2023"
                    },
                    {
                        toEmail : "Daksh",
                        emailName : "Order",
                        emailId : "423@abc.com",
                        ccEmail : "42@abc.com",
                        bccEmail : "44@abc.com",
                        fromEmail : "daksh@abc.com",
                        subject : "Reg - Order",
                        body : "Order isnt geting placed",
                        priority : "High",
                        status : "Delivered",
                        type : "Type4",
                        sendTime : "04-12-2024"
                    }
]